### ISSUE TITLE
腾讯COS报签名错误了，不买Pro能不能更新一下哈哈

### ISSUE THREAD

**Issue by tlerbao** [yanwenwu/think-filesystem-cloud#4]
`The Signature you specified is invalid.`

我怀疑是 qcloud/cos-sdk-v5 太新了，现在install的版本是2.6.x了
overtrue/flysystem-cos 又太旧了导致的

要不要把overtrue/flysystem-cos 更新到3.x 看看

万一买Pro呢 哈哈哈

**Comment by JaguarJack** [comment]
fork 吧
